# Generated by Django 5.0.6 on 2024-07-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_notifications_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
