# Generated by Django 5.0.6 on 2024-05-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/parking.jpeg', upload_to='user_images/'),
        ),
    ]
