# Generated by Django 5.0.6 on 2024-07-30 02:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='user_images/avatar.png', max_length=255, verbose_name='image'),
        ),
    ]
