# Generated by Django 5.0.6 on 2024-05-27 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('esp_id', models.CharField(default='Numero', max_length=10)),
                ('location', models.CharField(max_length=250)),
                ('slots', models.IntegerField(default=0)),
                ('occupancy', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, default='parking.jpeg', null=True, upload_to='parking_images/')),
                ('workingtime', models.CharField(max_length=100, null=True)),
                ('pricelvl1', models.IntegerField(null=True)),
                ('pricelvl2', models.IntegerField(null=True)),
                ('pricelvl3', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leprix', models.CharField(max_length=200, null=True)),
                ('startPrice', models.IntegerField(default=0)),
                ('monthPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TheCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.parkingarea')),
            ],
        ),
        migrations.AddField(
            model_name='parkingarea',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='park.thecity'),
        ),
    ]
