# Generated by Django 5.0.6 on 2024-05-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingarea',
            name='photo',
            field=models.ImageField(blank=True, default='images/parking.jpeg', null=True, upload_to='parking_images/'),
        ),
    ]
