# Generated by Django 5.0.6 on 2024-05-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_alter_parkingarea_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingarea',
            name='esp_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='photo',
            field=models.ImageField(default='images/parking.jpeg', upload_to='parking_images/'),
        ),
    ]
