# Generated by Django 5.0.6 on 2024-06-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_alter_parkingarea_esp_id_alter_parkingarea_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
