# Generated by Django 5.0.6 on 2024-06-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_slot_is_booked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('area', 'slot_number')},
        ),
    ]
