# Generated by Django 5.0.6 on 2024-06-26 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_slot_occupied_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('cleaner', models.ForeignKey(limit_choices_to={'groups__name': 'Cleaner'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.parkingarea')),
            ],
        ),
    ]
