# Generated by Django 5.0.6 on 2024-07-02 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_foundobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundobject',
            name='found_time',
        ),
        migrations.RemoveField(
            model_name='foundobject',
            name='is_claimed',
        ),
        migrations.AddField(
            model_name='foundobject',
            name='date_found',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foundobject',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foundobject',
            name='description',
            field=models.TextField(),
        ),
    ]
