# Generated by Django 5.0.6 on 2024-07-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0010_lostobjectrequest_lostobjectresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostobjectrequest',
            name='date_lost',
            field=models.DateField(blank=True, null=True),
        ),
    ]
