# Generated by Django 5.0.6 on 2024-07-02 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0011_alter_lostobjectrequest_date_lost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_area', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_requests/')),
                ('description', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LostObjectResponse',
        ),
    ]
