# Generated by Django 5.0.6 on 2024-07-02 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0012_lostrequest_delete_lostobjectresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundobject',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='found_objects/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostrequest',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='lost_requests/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LostObjectRequest',
        ),
    ]
