# Generated by Django 5.0.6 on 2024-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0013_alter_foundobject_image_alter_lostrequest_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostrequest',
            name='is_responded',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
