# Generated by Django 5.0.6 on 2024-07-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0014_lostrequest_is_responded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundobject',
            name='image',
            field=models.ImageField(default='images/avatar.jpeg', upload_to='found_objects/'),
        ),
        migrations.AlterField(
            model_name='lostrequest',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
    ]
