# Generated by Django 5.0.6 on 2024-07-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0016_slot_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingarea',
            name='location',
            field=models.URLField(max_length=250),
        ),
    ]
