# Generated by Django 5.0.6 on 2024-07-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0017_alter_parkingarea_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingarea',
            name='location',
            field=models.URLField(),
        ),
    ]
