# Generated by Django 5.0.6 on 2024-07-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0018_alter_parkingarea_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingarea',
            name='location',
            field=models.URLField(max_length=500),
        ),
    ]
