# Generated by Django 5.0.6 on 2024-07-03 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0019_alter_parkingarea_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingarea',
            name='share_location',
            field=models.URLField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
