# Generated by Django 5.0.6 on 2024-07-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0021_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
