# Generated by Django 5.0.6 on 2024-07-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0023_alter_foundobject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundobject',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
